server:
  port: 8090
  error:
    include-message: always
    whitelabel:
      enabled: false

app:
  name: fs-serv
  oauth:
    client-id: fs-serv
    client-secret: geol-po!@#
    token-signing-key: ${app.oauth.client-secret}:${app.oauth.client-id}

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  output:
    ansi:
      enabled: always
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 10000
      max-lifetime: 1800000
      pool-name: HikariCP
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        query:
          in_clause_parameter_padding: true
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fs_serv?zeroDateTimeBehavior=convertToNull&autoReconnection=true&autoReconnectForPools=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    username: fs_serv
    password: fs_serv
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: geolpo!@
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  config: classpath:log4j2/local.xml
